# Generated by Django 4.2.6 on 2023-12-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('head', models.CharField(max_length=50)),
                ('sub_head', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('receipt_number', models.CharField(max_length=20)),
                ('charge_by', models.CharField(max_length=50)),
                ('voucher', models.CharField(max_length=50)),
                ('paid_by', models.CharField(max_length=50)),
                ('claim_by', models.CharField(max_length=50)),
                ('comments', models.TextField()),
            ],
        ),
    ]
