# Generated by Django 4.2.6 on 2023-12-10 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='head',
            field=models.ForeignKey(limit_choices_to={'accountingentry__isnull': True}, on_delete=django.db.models.deletion.CASCADE, to='Accountapp.head'),
        ),
    ]
