# Generated by Django 4.2.6 on 2023-12-10 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0002_head_alter_accountingentry_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='paid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='charge_by',
            field=models.ForeignKey(limit_choices_to={'accountingentry__isnull': True}, on_delete=django.db.models.deletion.CASCADE, to='Accountapp.charge'),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='claim_by',
            field=models.ForeignKey(limit_choices_to={'accountingentry__isnull': True}, on_delete=django.db.models.deletion.CASCADE, to='Accountapp.claim'),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='paid_by',
            field=models.ForeignKey(limit_choices_to={'accountingentry__isnull': True}, on_delete=django.db.models.deletion.CASCADE, to='Accountapp.paid'),
        ),
    ]
