# Generated by Django 4.2.6 on 2023-12-11 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0003_charge_claim_paid_alter_accountingentry_charge_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingentry',
            name='charge_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'accountingentry__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accountapp.charge'),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='claim_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accountapp.claim'),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accountapp.paid'),
        ),
    ]
