# Generated by Django 4.2.6 on 2023-12-11 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0004_alter_accountingentry_charge_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingentry',
            name='charge_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accountapp.charge'),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accountapp.head'),
        ),
    ]
