# Generated by Django 4.2.6 on 2023-12-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0006_accountingentry_cash_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='vendors',
            field=models.ManyToManyField(blank=True, to='Accountapp.vendor'),
        ),
    ]
