# Generated by Django 4.2.6 on 2023-12-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0007_vendor_accountingentry_vendors'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingentry',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
