# Generated by Django 4.2.6 on 2023-12-15 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0008_accountingentry_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingentry',
            name='vendors',
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='vendors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accountapp.vendor'),
        ),
    ]
