# Generated by Django 4.2.6 on 2023-12-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0010_alter_accountingentry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingentry',
            name='date',
            field=models.DateField(),
        ),
    ]
