# Generated by Django 4.2.6 on 2023-12-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0011_alter_accountingentry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingentry',
            name='voucher',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
