# Generated by Django 4.2.6 on 2023-12-16 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0012_alter_accountingentry_voucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='sub_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accountapp.shead'),
        ),
    ]
