# Generated by Django 4.2.6 on 2023-12-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0013_shead_alter_accountingentry_sub_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingentry',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
