# Generated by Django 3.1.7 on 2024-01-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0016_auto_20231229_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charge',
            options={'verbose_name': 'Charge To', 'verbose_name_plural': 'Charge To'},
        ),
        migrations.AlterModelOptions(
            name='claim',
            options={'verbose_name': 'Claim By', 'verbose_name_plural': 'Claim By'},
        ),
        migrations.AlterModelOptions(
            name='paid',
            options={'verbose_name': 'Paid By', 'verbose_name_plural': 'Paid By'},
        ),
        migrations.AlterModelOptions(
            name='shead',
            options={'verbose_name': 'Sub Head', 'verbose_name_plural': 'Sub Heads'},
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='card_number',
            field=models.CharField(blank=True, default=0, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='accountingentry',
            name='instrument',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('online', 'Online Transfer'), ('card', 'Card')], max_length=10, null=True),
        ),
    ]
