# Generated by Django 3.1.7 on 2024-01-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0017_auto_20240101_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingentry',
            name='Do',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
